### ISSUE TITLE
期待回复

### ISSUE THREAD

**Issue by anshen666** [morningstarwang/MSRLSTM-open#1]
您好，我最近在研究cipher GAN,想和你相互交流一下。我的微信：loveanshen  我的QQ：519838354  期待您百忙中的回复！

**Comment by morningstarwang** [comment]
> 您好，我最近在研究cipher GAN,想和你相互交流一下。我的微信：loveanshen 我的QQ：519838354 期待您百忙中的回复！

抱歉，刚看到，已加。
